Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -22,16 +22,19 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install flake8  # Ensure flake8 is installed
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+    - name: Run script and check output
+      run: |
+        python main.py  # Replace this command with your actual script execution command
+        if [ -f Final.xlsx ]; then
+          echo "Final.xlsx exists."
+        else
+          echo "Final.xlsx does not exist."
+          exit 1  # This will fail the build if Final.xlsx is not found
     - name: Lint with flake8
       run: |
-        # stop the build if there are Python syntax errors or undefined names
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
-
-
 
   build-macos:
     runs-on: macos-latest
@@ -44,12 +47,16 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install flake8  # Ensure flake8 is installed
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+    - name: Run script and check output
+      run: |
+        python main.py  # Replace this command with your actual script execution command
+        if [ -f Final.xlsx ]; then
+          echo "Final.xlsx exists."
+        else
+          echo "Final.xlsx does not exist."
+          exit 1  # This will fail the build if Final.xlsx is not found
     - name: Lint with flake8
       run: |
-        # stop the build if there are Python syntax errors or undefined names
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
-
